---
title: "Multiple testing with continuous covariates"
author: "Nikos Ignatiadis"
date: "`r doc_date()`"
output:
  BiocStyle::html_document
vignette: >
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

### Load packages

```{r  message=FALSE,result=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
```

## Colors and method names used throughout 

```{r}
# (from https://github.com/dill/beyonce)
beyonce_colors <- c("#b72da0", "#7c5bd2", "#0097ed","#00c6c3",
                    "#9cd78a", "#f7f7a7", "#ebab5f", "#e24344",
                    "#04738d")#,"#d8cdc9")
beyonce_colors[6] <- c("#dbcb09") # thicker yellow
pretty_colors <- beyonce_colors[c(2,1,3:5)]
```

```{r}
#"Black" -> BH + shape 20
#beyonce 2 -> IHW-CARS + shape 12
#beyonce 1 -> IHW Grenander  + shape 13
#CARS beyonce -> 3 + shape 0
#CARS-sparse beyonce -> 4    + shape 1  
method_names_saved<- c("BH", "Lfdr-oracle", "Lfdr-EM", "AdaPT", "IHW-BetaMix", "IHW-Grenander")
method_names <- c("BH", "Clfdr-oracle", "Clfdr-EM", "AdaPT", "IHW-Storey-BetaMix", "IHW-BH-Grenander")
method_colors <- c("Black", beyonce_colors[c(3,4, 6, 2, 1)])
names(method_colors) <- method_names
method_shapes <- c(20, 0,1, 2, 12, 13)
names(method_shapes) <- method_names

```

# Main simulation

## Load result files

```{r}
betamix_r <- c(readRDS(file="../precomputed_results/betamix_simulations.Rds"),
              readRDS(file="../precomputed_results/betamix_simulations_lfdr.Rds"))
```

```{r}
betamix_res <-  bind_rows(unlist(betamix_r, recursive = FALSE)) %>% 
  group_by(method, m, mu_slope) %>%
  summarize(FDR = mean(FDP, na.rm=TRUE),
            Power=mean(pow, na.rm=TRUE),
            n=sum(!is.na(FDP)),
            se_power = sd(pow, na.rm=TRUE)/sqrt(n)) %>%
  arrange(mu_slope, desc(Power)) %>% 
  ungroup() %>%
  mutate(method = factor(method, levels=method_names_saved)) %>% 
  mutate(method = fct_recode(method, "Clfdr-oracle"="Lfdr-oracle", 
                                     "Clfdr-EM"="Lfdr-EM",
                                     "IHW-Storey-BetaMix"="IHW-BetaMix",
                                     "IHW-BH-Grenander"="IHW-Grenander"))
```

## Plot FDR

```{r width=6/1.2,height=4/1.2}
fdr_betamix_plot <- ggplot(betamix_res, aes(x=mu_slope, y=FDR,shape=method, col=method)) + 
  geom_line() + geom_point() + 
  ylim(0, 0.15) + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  geom_hline(yintercept=0.1, linetype=2)+
  xlab(expression(bar(beta)))+
  theme_cowplot() +
  theme(legend.position = "none")

fdr_betamix_plot
```

```{r eval=FALSE}
ggsave(fdr_betamix_plot, filename="fdr_betamix.pdf", width=6/1.2,height=4/1.2)
```

## Plot Power

```{r width=7.73/1.2,height=4/1.2}
power_betamix_plot <- ggplot(betamix_res, aes(x=mu_slope, y=Power, shape=method, col=method)) + 
  geom_line() + geom_point() + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  xlab(expression(bar(beta)))+
  scale_y_log10(breaks = c(0.003, 0.01, 0.025, 0.05, 0.1, 0.2, 0.4)) + 
  ylab("Power (log scale)") + 
  theme_cowplot()  +
  theme(legend.title=element_blank())

power_betamix_plot
```

```{r eval=FALSE}
ggsave(power_betamix_plot, filename="power_betamix.pdf", width=7.73/1.2,height=4/1.2)
```

# Simulation demonstrating power under one-sided alternatives 

## Load result files

```{r}
betamix_onesided_r <- readRDS(file="../precomputed_results/betamix_onesided_simulations.Rds")
```

```{r}
betamix_onesided_res <-  bind_rows(unlist(betamix_onesided_r, recursive = FALSE)) %>% 
  group_by(method, m, prob_one_sided) %>%
  summarize(FDR = mean(FDP, na.rm=TRUE),
            Power=mean(pow, na.rm=TRUE),
            n=sum(!is.na(FDP)),
            se_power = sd(pow, na.rm=TRUE)/sqrt(n)) %>%
  arrange(prob_one_sided, desc(Power)) %>% 
  ungroup() %>%
  mutate(method = factor(method, levels=method_names_saved)) %>%
  mutate(method = fct_recode(method, "Clfdr-oracle"="Lfdr-oracle", 
                                     "Clfdr-EM"="Lfdr-EM",
                                     "IHW-Storey-BetaMix"="IHW-BetaMix",
                                     "IHW-BH-Grenander"="IHW-Grenander"))
```

## Plot FDR

```{r width=6/1.8,height=4/1.4}
fdr_betamix_onesided_plot <- ggplot(betamix_onesided_res, aes(x=prob_one_sided, y=FDR,shape=method, col=method)) + 
  geom_line() + geom_point() + 
  ylim(0, 0.15) + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  geom_hline(yintercept=0.1, linetype=2)+
  xlab(expression(kappa))+
  theme_cowplot() +
  theme(legend.position = "none")

fdr_betamix_onesided_plot
```

```{r eval=FALSE}
ggsave(fdr_betamix_onesided_plot, filename="fdr_betamix_onesided.pdf", width=6/1.8,height=4/1.4)
```

## Plot Power

```{r width=7.73/1.6,height=4/1.4}
power_betamix_onesided_plot <- ggplot(betamix_onesided_res, aes(x=prob_one_sided, y=Power, shape=method, col=method)) + 
  geom_line() + geom_point() + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  xlab(expression(kappa))+
  ylab("Power") + 
  ylim(0,0.35) + 
  theme_cowplot()  +
  theme(legend.title=element_blank()) #theme(legend.position="none")

power_betamix_onesided_plot
```

```{r eval=FALSE}
#ggsave(power_betamix_onesided_plot, filename="power_betamix_onesided_plot_nolegend.pdf", width=6/1.8,height=4/1.4)
ggsave(power_betamix_onesided_plot, filename="power_betamix_onesided_plot.pdf", width=7.73/1.6,height=4/1.4)
```



## Plot of null densities

```{r}
null_density_df <- function(p){
  xs <- seq(0.01,0.99, length=100)
  f_marg <-  p*dbeta(xs, 1, 0.5) + (1-p)
  data.frame(x=xs, f=f_marg, p=p)
}

p_bars <- seq(0,0.1, length=6)
null_densities_df <- bind_rows( lapply(p_bars, null_density_df)) %>% 
                     mutate( p = factor(p, levels = rev(p_bars)))
```

```{r width=5.3/1.4,height=4/1.4}
null_plots <- ggplot(null_densities_df, aes(x=x, y=f, col=p)) +
                 geom_line() + 
                 theme_cowplot() +
                 scale_y_continuous(expand = c(0, 0), limits=c(0,2), breaks=c(0.5,1,1.5, 2)) +
                 scale_x_continuous(expand = c(0, 0), limits=c(0,1), breaks=c(0,0.5,1)) + 
                 scale_color_manual(values =  brewer.pal(8, "Purples")[3:8])+
                 ylab("density") + 
                 xlab("p-value") + 
                 guides(color=guide_legend(title=expression(kappa)))
null_plots
```

```{r eval=FALSE}
ggsave(null_plots, filename="super_uniform_densities_plot.pdf", width=5.3/1.4,height=4/1.4)
```
