---
title: "Grouped multiple testing"
author: "Nikos Ignatiadis"
date: "`r doc_date()`"
output:
  BiocStyle::html_document
vignette: >
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

### Load packages

```{r  message=FALSE,result=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())
```

## Colors and method names used throughout 

```{r}
beyonce_colors <- c("#b72da0", "#7c5bd2", "#0097ed","#00c6c3",
                    "#9cd78a", "#f7f7a7", "#ebab5f", "#e24344",
                    "#04738d")#,"#d8cdc9")
beyonce_colors[6] <- c("#dbcb09") # thicker yellow
pretty_colors <- beyonce_colors[c(2,1,3:5)]


method_names <- c("BH", "SBH", "Clfdr", "GBH-Storey", "IHW-GBH", "IHW-Grenander-Storey", "SABHA")
method_names_print <- c("BH", "SBH", "Clfdr", "GBH", "IHW-GBH", "IHW-Storey-Grenander", "SABHA")

method_colors <- c("Black", beyonce_colors[c(3:5, 2, 1, 6)])
names(method_colors) <- method_names_print

method_shapes <- c(20, 0,1,2, 12, 13,2 )
names(method_shapes) <- method_names_print
```

##  Global null simulations from introduction

```{r}
group_null_res <- readRDS(file= "../precomputed_results/group_null_res_intro.Rds")
```

```{r}
summarize_group_null_sim_res <- group_by(group_null_res, method, K) %>%
  summarize(FDR = mean(FDP))
```

```{r fig.width=6, fig.height=2.5}
fdr_null_plot <- ggplot(summarize_group_null_sim_res, 
                        aes(x=K, y=FDR,col=method, shape=method)) + geom_line() +
  geom_point() +
  xlab("Number of groups (G)") + 
  ylim(0, 0.4) + 
  geom_hline(yintercept=0.2, linetype=2) + 
  scale_x_log10() + 
  scale_color_manual(values=pretty_colors[1:2]) + 
  theme_cowplot() + 
  theme(legend.title=element_blank())

fdr_null_plot
```
```{r eval=FALSE}
ggsave(fdr_null_plot, filename="intro_fdr_null_plot.pdf", width=6,height=2.5)
```

##  Global null simulations



```{r}
grouped_null <- readRDS(file="../precomputed_results/grouped_null_simulations_all_methods.Rds")  
```

```{r}
summarize_group_null_sim_res <- group_by(grouped_null, method, K_coarse) %>%
  summarize(FDR = mean(FDP), Power=mean(pow), n_monte_carlo = n()) %>%
  arrange(K_coarse, desc(Power)) %>% 
  ungroup() %>%
  filter(method %in% method_names) %>%
  mutate(method = factor(method, levels=method_names)) %>%
  mutate(method = fct_recode(method, 
                            "GBH"="GBH-Storey",
                            "IHW-Storey-Grenander" = "IHW-Grenander-Storey"))

```

```{r  fig.width=5.6, fig.height=2.4}
fdr_grouped_null_plot <- ggplot(summarize_group_null_sim_res, aes(x=K_coarse, y=FDR,shape=method, col=method)) + 
  geom_line() + geom_point() + 
  scale_x_log10(breaks=c(2,5, 10, 20,40)) + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  geom_hline(yintercept=0.1, linetype=2)+
  xlab("Number of groups (G)") +
  theme_cowplot() + 
  theme(legend.title=element_blank())
fdr_grouped_null_plot
```

```{r eval=FALSE}
#fdr_grouped_null_plot <- fdr_grouped_null_plot + theme(legend.position = "none")
#ggsave(fdr_grouped_null_plot, filename="fdr_grouped_null_plot.pdf", width=3.4,height=2.8)
```



## Simulations with signal

```{r}
group_sim_res <- readRDS(file= "../precomputed_results/grouped_simulations_signal.Rds")
```

```{r}
summarize_group_sim_res <- group_by(group_sim_res, method, K_coarse) %>%
                             summarize(FDR = mean(FDP), Power=mean(pow)) %>%
                             arrange(K_coarse, desc(Power)) %>% 
                             ungroup() %>%
                             filter(method %in% method_names) %>%
                             mutate(method = factor(method, levels=method_names)) %>%
                             mutate(method = fct_recode(method, 
                                  "GBH"="GBH-Storey",
                                  "IHW-Storey-Grenander" = "IHW-Grenander-Storey"))
```

### Plot FDR

```{r fig.width=5.6, fig.height=2.4}
fdr_grouped_signal_plot <- ggplot(summarize_group_sim_res, aes(x=K_coarse, y=FDR,shape=method, col=method)) + 
  geom_line() + geom_point() + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  geom_hline(yintercept=0.1, linetype=2)+
  xlab("Number of groups (G)")+ 
  scale_x_log10(breaks=c(2,5, 10, 20,40)) +   
  theme_cowplot() +
  theme(legend.title=element_blank())
fdr_grouped_signal_plot
```

```{r eval=FALSE}
##fdr_grouped_signal_plot <-  fdr_grouped_signal_plot + theme(legend.position = "none")
#ggsave(fdr_grouped_signal_plot, filename="fdr_grouped_signal_plot.pdf", width=3.4,height=2.8)
```

### Plot Power

```{r fig.width=5.6, fig.height=2.4}
power_grouped_signal_plot <- ggplot(summarize_group_sim_res, aes(x=K_coarse, y=Power, shape=method, col=method)) + 
                                geom_line() + geom_point() + 
                                scale_color_manual(values=method_colors) + 
                                scale_shape_manual(values=method_shapes) +
                                xlab("Number of groups (G)")  +
                                scale_x_log10(breaks=c(2,5, 10, 20,40)) +   
                                theme_cowplot() + 
                                theme(legend.title=element_blank())

power_grouped_signal_plot
```

```{r eval=FALSE}
ggsave(power_grouped_signal_plot, filename="power_grouped_signal_plot.pdf", width=5.6,height=2.8)
```

